Criação de provas dinâmicas/cegas
luisteofilo/estg-esof2-turno-bc pull request #26
Opened 2024-06-26 13:57 UTC by Xicojfc

Descrição: Desenvolver as funcionalidades para a criação de provas dinâmicas/cegas(Blind events):

O organizador cria a prova dinâmica/cega.
O organizador pode adicionar utilizadores para participar.
O organizador escolhe a data para a prova dinâmica/cega.
O organizador pode participar na prova.
O utilizador adiciona vinhos à prova.
Os utilizadores não conseguem visualizar os vinhos escolhidos por outros participantes.
Os utilizadores não conseguirá escolher um vinho já escolhido por outro utilizador.

2024-06-26 14:29 UTC, leticialoureiro04 requested changes
Tentar resolver os merge conflicts.

2024-06-26 18:29 UTC, leticialoureiro04 approved these changes

2024-06-26 19:48 UTC, Xurape requested changes
Please, resolve the conflict issues before moving to the merge. There's a lot of files that are getting conflict.

2024-06-28 13:27 UTC, Xurape approved these changes
Working great and as intended! Great job, you can now merge!

2024-06-28 13:27 UTC, merged