Implementação de página para Leadboards de Users e Vinhos
luisteofilo/estg-esof2-turno-bc pull request #29
Opened 2024-06-26 22:45 UTC by MistaPaulo

Criação das classes em WebAPI e Frontend necessárias para fornecer dados à página Leaderboards.razor com as tabelas de leaderboards dos vinhos e dos users.

2024-06-26 22:50 UTC, Guimaraes04 requested changes
As I can see, you have unresolved merge conflicts, make sure you fix them before merging!

2024-06-26 23:52 UTC, MistaPaulo commented
Já resolvi os conflitos, no entanto tenho uma dúvida em relação à classe WebAPI/Program.cs.

Localmente, só estava a conseguir dar build a WebAPI se substituí-se a linha
_______________________________________________________________
builder.Services.AddDbContext<ApplicationDbContext>();
_______________________________________________________________
por:

![image](https://github.com/luisteofilo/estg-esof2-turno-bc/assets/170202749/12dee8da-6359-49bf-b5ef-9f04806cce10)

2024-06-28 01:17 UTC, Xurape commented
Will test the feature tomorrow.

2024-06-30 10:28 UTC, Xurape approved these changes
Looks good to me, can merge 👍

2024-06-30 12:58 UTC, merged